<!doctype html>
<html lang="es">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#050b12">
  <title>Protocolo del traje | Cris</title>
  <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Bangers&family=Montserrat:wght@500;700;800&display=swap" rel="stylesheet">
  <style>
    *{box-sizing:border-box}body{min-height:100svh;margin:0;display:grid;place-items:center;padding:max(24px,env(safe-area-inset-top)) max(18px,env(safe-area-inset-right)) max(24px,env(safe-area-inset-bottom)) max(18px,env(safe-area-inset-left));background:radial-gradient(circle at 50% 25%,#123b62,transparent 36%),#050b12;color:#eaf7ff;font-family:Montserrat,sans-serif}.scan{position:fixed;inset:0;pointer-events:none;opacity:.1;background:repeating-linear-gradient(0deg,transparent 0 4px,#a9e6ff 5px)}.panel{position:relative;width:min(100%,460px);padding:38px;border:1px solid #3c83b5;background:rgba(4,16,29,.92);box-shadow:0 0 45px #0a5d9988,inset 0 0 30px #0a5d9933}.spider{width:62px;aspect-ratio:1;margin:auto;background:#ed2031;clip-path:polygon(50% 0,61% 29%,86% 12%,75% 40%,100% 50%,75% 58%,88% 85%,61% 70%,50% 100%,39% 70%,12% 85%,25% 58%,0 50%,25% 40%,14% 12%,39% 29%)}.status{text-align:center;color:#76d4ff;font-size:.65rem;font-weight:800;letter-spacing:.2em}h1{margin:18px 0 8px;text-align:center;color:#ed2031;font:3.2rem/.85 Bangers,sans-serif;letter-spacing:.04em;text-shadow:2px 2px #fff}p{text-align:center;color:#a9c9dc;font-size:.78rem;line-height:1.6}label{display:block;margin:25px 0 7px;color:#76d4ff;font-size:.65rem;font-weight:800;letter-spacing:.12em}input{width:100%;min-height:48px;padding:14px;border:1px solid #3c83b5;outline:none;background:#071523;color:#fff;font:700 1rem Montserrat,sans-serif;letter-spacing:.12em;text-transform:uppercase}input:focus{border-color:#76d4ff;box-shadow:0 0 12px #2c9ed966}.error{margin:8px 0;color:#ff8390;text-align:left}button{width:100%;min-height:48px;margin-top:15px;padding:15px;border:0;background:#ed2031;color:#fff;cursor:pointer;font:800 .72rem Montserrat,sans-serif;letter-spacing:.12em;box-shadow:4px 4px #000}.back{display:block;min-height:44px;margin-top:20px;color:#8dcbe8;text-align:center;font-size:.68rem;text-decoration:none}@media(max-width:420px){body{place-items:center;padding-left:14px;padding-right:14px}.panel{padding:28px 18px}.spider{width:52px}h1{font-size:2.7rem}.status{font-size:.55rem;letter-spacing:.13em}}
  </style>
</head>
<body><div class="scan"></div><main class="panel"><div class="spider"></div><p class="status">SISTEMA STARK · IDENTIDAD REQUERIDA</p><h1>PROTOCOLO<br>DEL TRAJE</h1><p>Introduce tu clave de héroe para consultar los registros de la misión.</p><form method="POST" action="{{ route('rsvp.login.store') }}">@csrf<label for="key">CLAVE DE ACCESO</label><input id="key" name="key" type="password" autocomplete="current-password" autofocus required>@error('key')<p class="error">{{ $message }}</p>@enderror<button type="submit">INICIAR PROTOCOLO</button></form><a class="back" href="{{ route('home') }}">← Volver a la invitación</a></main></body>
</html>
